### ISSUE TITLE
Ceiling fan not rendering on Fabric

### ISSUE THREAD

**Issue by Axtasium** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#81]
I know the 1.21.4 version for fabric just came out, but I cant figure out for the life of me how to get wheat flour and how to use the cutting board. I checked and you can 100% cut bread on it using a knife, but it just doesn't do anything for me. Is it as simple as right clicking on bread on the cutting board with a knife or am i missing something?

Some other weirdness as well.

1. breaking anything from this mod drops nothing at the moment, so you cant get anything back you place. 

2. The ceiling fans have no blades, though I'm not sure if that's the mod or something else.

3. The jar, when punching it to get cookies out, retains damage data so punching it to get all the cookies breaks the jar. This is specifically if you put one in and right after, without punching anything else, try and take a cookie out of the jar.

**Comment by MrCrayfish** [comment]
> breaking anything from this mod drops nothing at the moment, so you cant get anything back you place.

Thanks. Fixed in https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/723a8cceec78304f0903efcfc1fd5aa9067a949d

> The ceiling fans have no blades, though I'm not sure if that's the mod or something else.

Seems to be an issue in Fabric API. I've reported it here: https://github.com/FabricMC/fabric/issues/4332

> The jar, when punching it to get cookies out, retains damage data so punching it to get all the cookies breaks the jar. This is specifically if you put one in and right after, without punching anything else, try and take a cookie out of the jar.

Thanks. Fixed in 986e25c783142796d1484efec0825ebdb74cacfb

**Comment by Axtasium** [comment]
I still cant seem to cut bread on a cutting board. I was able to combine stuff, but right clicking bread with a knife on the cutting board doesn't do anything. I don't know if I'm missing something or that is actually a bug/issue.
yeah i just checked the slicing recipes and none of them work. I can put the item on the cutting board, but am completely unable to actually cut anything.

**Comment by MrCrayfish** [comment]
> I still cant seem to cut bread on a cutting board. I was able to combine stuff, but right clicking bread with a knife on the cutting board doesn't do anything. I don't know if I'm missing something or that is actually a bug/issue.
yeah i just checked the slicing recipes and none of them work. I can put the item on the cutting board, but am completely unable to actually cut anything.

Ahh, I missed that part. In the future, can you please split into separate issues instead of bundling. Thank you. I'll look into it

**Comment by josh321-dev** [comment]
any update on fan blades not rendering on fabric 1.21.4 ? cause its not rendering for me either @MrCrayfish

**Comment by MrCrayfish** [comment]
You can follow the issue on Fabric's issue tracker: https://github.com/FabricMC/fabric/issues/4332

**Comment by MrCrayfish** [comment]
Fixed. Make sure you are using Fabric API 0.114.1 or higher.
